[package]
name = "oidc4vci-rs"
version = "0.1.0"
authors = ["Spruce Systems, Inc."]
edition = "2021"
license = "Apache-2.0"
description = "Core library for Verifiable Credentials and Decentralized Identifiers."
repository = "https://github.com/spruceid/oidc4vci-rs/"

[dependencies]
ssi = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
percent-encoding = { version = "2.1" }
rand = { version = "0.8" }
chrono = { version = "0.4", features = ["serde"] }
base64 = "0.12"
